sudo: required
services:
  - docker

before_install:
  - docker build -t salinabookshelf/docker-react -f Dockerfile.dev .

script:
  - docker run salinabookshelf/docker-react npm run test -- --coverage